pipeline:
  name: Java Goof CI Pipeline
  identifier: java_goof_ci_pipeline
  projectIdentifier: my_project
  orgIdentifier: my_org
  stages:
    - stage:
        name: Build and Snyk Stage
        identifier: build_and_snyk_stage
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: Docker
            spec:
              connectorRef: my_docker_connector
          execution:
            steps:
              - step:
                  name: Build with Maven
                  identifier: build_with_maven
                  type: Run
                  spec:
                    connectorRef: my_maven_connector
                    image: maven:3.8.6-openjdk-11
                    shell: Bash
                    command: |
                      mvn clean install
              - step:
                  name: Snyk Security Scan
                  identifier: snyk_scan
                  type: Run
                  spec:
                    connectorRef: my_snyk_connector
                    image: snyk/snyk-cli:latest
                    shell: Bash
                    command: |
                      snyk test
