pipeline:
  name: Java Goof Pipeline
  identifier: java_goof_pipeline
  projectIdentifier: my_project
  orgIdentifier: my_org
  stages:
    - stage:
        name: Build Stage
        identifier: build_stage
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: my_k8s_connector
              namespace: default
              volumes: []
          execution:
            steps:
              - step:
                  name: Build with Maven
                  identifier: build_with_maven
                  type: Run
                  spec:
                    connectorRef: my_maven_connector
                    image: maven:3.8.6-openjdk-11
                    shell: Bash
                    command: |
                      mvn clean install
              - step:
                  name: Docker Build and Push
                  identifier: docker_build_and_push
                  type: BuildAndPushDockerRegistry
                  spec:
                    connectorRef: my_dockerhub_connector
                    repo: my-docker-repo/java-goof
                    tags:
                      - latest
                    context: ./
                    dockerfile: ./Dockerfile
    - stage:
        name: Deploy Stage
        identifier: deploy_stage
        type: CD
        spec:
          infrastructure:
            environmentRef: my_environment
            infrastructureDefinition:
              type: KubernetesDirect
              spec:
                connectorRef: my_k8s_connector
                namespace: default
          execution:
            steps:
              - step:
                  name: Kubernetes Apply
                  identifier: k8s_apply
                  type: Apply
                  spec:
                    resources:
                      - /path/to/k8s/deploy.yaml
